/*
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Based entirely on articles from http://www.channelfireball.com/.
// If you disagree with a card valuation, feel free to open a ticket.

var card_data = {
    // Gods: TODO
    // Nyx: TODO
    // Theros
    'gray merchant of asphodel': 'Good',
    'arbor colossus': 'Best',
    'pyxis of pandemonium': 'Filler',
    'akroan hoplite': 'Filler',
    'omenspeaker': 'Playable',
    'cavern lampad': 'Playable',
    'anger of the gods': 'Playable',
    'breaching hippocamp': 'Bad',
    'underworld cerberus': 'Good',
    'triton tactics': 'Playable',
    'time to feed': 'Playable',
    'scholar of athreos': 'Filler',
    'aqueous form': "Playable",
    'flamecast wheel': 'Filler',
    "warriors' lesson": "Playable",
    'asphodel wanderer': 'Bad',
    'read the bones': 'Playable',
    'master of waves': 'Good',
    "pharika's mender": 'Filler',
    'gainsay': 'Bad',
    'two-headed cerberus': 'Playable',
    'stymied hopes': 'Filler',
    'sealock monster': 'Playable',
    'lash of the whip': 'Playable',
    'ink dissolver': 'Filler',
    'priest of iroas': 'Filler',
    'stormbreath dragon': 'Best',
    'sylvan caryatid': 'Good',
    "nylea's emissary": 'Good',
    'hythonia the cruel': 'Good',
    'demolish': 'Bad',
    'loathsome catoblepas': 'Filler',
    "witches' eye": 'Filler',
    "titan's strength": "Playable",
    'wild celebrants': 'Bad',
    'lightning strike': 'Good',
    'glare of heresy': 'Bad',
    "viper's kiss": 'Bad',
    'favored hoplite': 'Filler',
    'polukranos, world eater': 'Best',
    'returned phalanx': 'Filler',
    'destructive revelry': 'Filler',
    "messenger's speed": 'Bad',
    "nylea's presence": 'Filler',
    'mnemonic wall': 'Bad',
    'fleecemane lion': 'Good',
    'prescient chimera': 'Playable',
    'battlewise hoplite': 'Playable',
    'wavecrash triton': 'Playable',
    'nykthos, shrine to nyx': 'Filler',
    'nylea, god of the hunt': 'Playable',
    'heliod, god of the sun': 'Playable',
    'peak eruption': 'Bad',
    'hunt the hunter': 'Bad',
    'vanquish the foul': 'Bad',
    'scourgemark': "Playable",
    'boon of erebos': "Playable",
    'horizon chimera': 'Playable',
    'shipbreaker kraken': 'Good',
    'lost in a labyrinth': 'Bad',
    'sip of hemlock': 'Playable',
    'swan song': 'Bad',
    'setessan griffin': 'Filler',
    "sea god's revenge": 'Great',
    'phalanx leader': 'Great',
    'dragon mantle': "Playable",
    'griptide': 'Good',
    'chosen by heliod': "Playable",
    'satyr rambler': 'Bad',
    'benthic giant': 'Bad',
    'shipwreck singer': 'Playable',
    'feral invocation': 'Playable',
    'temple of triumph': 'Filler',
    'agent of horizons': 'Filler',
    'insatiable harpy': 'Playable',
    'divine verdict': 'Playable',
    "voyage's end": 'Good',
    'nessian courser': 'Playable',
    'decorated griffin': 'Bad',
    'horizon scholar': 'Playable',
    'spark jolt': 'Bad',
    'psychic intrusion': 'Filler',
    "hero's downfall": 'Good',
    'bronze sable': 'Filler',
    'voyaging satyr': 'Good',
    'setessan battle priest': 'Bad',
    'lagonna-band elder': 'Filler',
    'triton fortune hunter': 'Playable',
    "karametra's acolyte": 'Playable',
    'savage surge': "Playable",
    'soldier of the pantheon': 'Playable',
    'ashen rider': 'Filler',
    "thassa's emissary": 'Good',
    'triad of fates': 'Playable',
    'celestial archon': 'Best',
    'chained to the rocks': 'Playable',
    'fleshmad steed': 'Bad',
    'satyr hedonist': 'Filler',
    'thoughtseize': 'Playable',
    'arena athlete': 'Playable',
    'guardians of meletis': 'Filler',
    'prophet of kruphix': 'Good',
    'rageblood shaman': 'Playable',
    'sedge scorpion': 'Playable',
    "artisan's sorrow": 'Filler',
    'opaline unicorn': 'Filler',
    "erebos's emissary": 'Good',
    'centaur battlemaster': 'Playable',
    'akroan crusader': 'Bad',
    'whip of erebos': 'Good',
    'bow of nylea': 'Best',
    'ashiok, nightmare weaver': 'Good',
    'hammer of purphoros': 'Best',
    'march of the returned': 'Bad',
    'yoked ox': 'Bad',
    'fate foretold': "Playable",
    'silent artisan': 'Bad',
    'nimbus naiad': 'Good',
    'stoneshock giant': 'Playable',
    "thassa's bounty": 'Bad',
    'baleful eidolon': 'Playable',
    'ordeal of erebos': 'Playable',
    'hopeful eidolon': 'Playable',
    'akroan horse': 'Filler',
    'cutthroat maneuver': 'Bad',
    'pheres-band centaurs': 'Filler',
    'mistcutter hydra': 'Good',
    'coordinated assault': 'Playable',
    'tormented hero': 'Playable',
    'unknown shores': 'Filler',
    'anthousa, setessan hero': 'Playable',
    'satyr piper': 'Bad',
    'staunch-hearted warrior': 'Playable',
    'battlewise valor': "Playable",
    'commune with the gods': 'Filler',
    'rage of purphoros': 'Playable',
    'defend the hearth': 'Bad',
    'anax and cymede': 'Good',
    'ordeal of heliod': 'Playable',
    "prowler's helm": 'Filler',
    'triton shorethief': 'Bad',
    'xenagos, the reveler': 'Good',
    'temple of deceit': 'Filler',
    'dark betrayal': 'Bad',
    'hundred-handed one': 'Good',
    'nessian asp': 'Good',
    'boon satyr': 'Best',
    'borderland minotaur': 'Playable',
    'bident of thassa': 'Good',
    'leonin snarecaster': 'Filler',
    'fabled hero': 'Best',
    'curse of the swine': 'Playable',
    'rescue from the underworld': 'Bad',
    'ill-tempered cyclops': 'Playable',
    'nighthowler': 'Good',
    'titan of eternal fire': 'Filler',
    "traveler's amulet": 'Filler',
    'fade into antiquity': 'Bad',
    "elspeth, sun's champion": 'Best',
    'spear of heliod': 'Best',
    'medomai the ageless': 'Good',
    'blood-toll harpy': 'Playable',
    'colossus of akros': 'Filler',
    'evangel of heliod': 'Playable',
    'ordeal of nylea': 'Playable',
    "ephara's warden": 'Bad',
    'abhorrent overlord': 'Best',
    'fanatic of mogis': 'Playable',
    'felhide minotaur': 'Filler',
    'ray of dissolution': 'Filler',
    'leafcrown dryad': 'Good',
    'agent of the fates': 'Best',
    'fleetfeather sandals': 'Filler',
    'temple of mystery': 'Filler',
    'labyrinth champion': 'Playable',
    'keepsake gorgon': 'Great',
    'erebos, god of the dead': 'Playable',
    'crackling triton': 'Filler',
    "purphoros's emissary": 'Playable',
    'nemesis of mortals': 'Playable',
    'ember swallower': 'Good',
    'sentry of the underworld': 'Playable',
    'vulpine goliath': 'Filler',
    'spellheart chimera': 'Filler',
    'ordeal of thassa': 'Playable',
    'flamespeaker adept': 'Playable',
    'shredding winds': 'Bad',
    'returned centaur': 'Filler',
    'vaporkin': 'Playable',
    'tymaret, the murder king': 'Filler',
    'gods willing': 'Playable',
    'coastline chimera': 'Filler',
    'temple of abandon': 'Filler',
    'disciple of phenax': 'Playable',
    'anvilwrought raptor': 'Filler',
    "nylea's disciple": 'Playable',
    'burnished hart': 'Filler',
    'traveling philosopher': 'Filler',
    'spearpoint oread': 'Playable',
    'kragma warcaller': 'Filler',
    'magma jet': 'Playable',
    'reaper of the wilds': 'Good',
    'observant alseid': 'Playable',
    'firedrinker satyr': 'Bad',
    'cavalry pegasus': 'Filler',
    'dauntless onslaught': 'Playable',
    "heliod's emissary": 'Good',
    'deathbellow raider': 'Filler',
    'prognostic sphinx': 'Best',
    'daxos of meletis': 'Good',
    'gift of immortality': 'Bad',
    'meletis charlatan': 'Playable',
    'portent of betrayal': 'Bad',
    'thassa, god of the sea': 'Playable',
    'polis crusher': 'Good',
    'last breath': 'Bad',
    'minotaur skullcleaver': 'Filler',
    'chronicler of heroes': 'Playable',
    'reverent hunter': 'Playable',
    'boulderfall': 'Bad',
    "mogis's marauder": 'Playable',
    'artisan of forms': 'Playable',
    'wingsteed rider': 'Good',
    'purphoros, god of the forge': 'Playable',
    "pharika's cure": 'Playable',
    'temple of silence': 'Filler',
    'steam augury': 'Filler',
    'ordeal of purphoros': 'Playable',
    'annul': 'Bad',
    // M15
    'perilous vault': "Playable",
    'siege dragon': 'Good',
    'wall of limbs': "Filler",
    'grindclock': "Filler",
    'yavimaya coast': 'Playable',
    'wall of fire': "Filler",
    'ulcerate': "Good",
    'resolute archangel': 'Playable',
    'profane memento': 'Bad',
    'ancient silverback': 'Playable',
    'encrust': "Playable",
    'might makes right': "Filler",
    'preeminent captain': 'Playable',
    'feast on the fallen': "Filler",
    "brawler's plate": "Filler",
    'ensoul artifact': "Playable",
    'heat ray': "Good",
    'forge devil': 'Playable',
    'flesh to dust': 'Playable',
    'peel from reality': 'Playable',
    'midnight guard': "Playable",
    'chord of calling': "Playable",
    'paragon of open graves': 'Playable',
    'crippling blight': "Playable",
    'aggressive mining': "Filler",
    'invisibility': 'Bad',
    'into the void': 'Playable',
    'kinsbaile skirmisher': 'Playable',
    'triplicate spirits': 'Great',
    'haunted plate mail': 'Good',
    'torch fiend': "Playable",
    'belligerent sliver': "Playable",
    'chasm skulker': 'Good',
    'titanic growth': 'Playable',
    "miner's bane": "Playable",
    'research assistant': "Playable",
    'master of predicaments': 'Good',
    'scuttling doom engine': 'Good',
    'lightning strike': 'Great',
    'sanctified charge': 'Playable',
    'sungrace pegasus': 'Playable',
    'shrapnel blast': "Filler",
    'soul of shandalar': 'Best',
    'welkin tern': 'Playable',
    'roaring primadox': 'Playable',
    'hushwing gryff': 'Playable',
    'vineweft': "Filler",
    'verdant haven': "Filler",
    'stormtide leviathan': 'Playable',
    'solemn offering': "Filler",
    'seraph of the masses': 'Playable',
    'congregate': "Filler",
    'netcaster spider': 'Playable',
    'charging rhino': "Playable",
    'first response': "Playable",
    'invasive species': 'Playable',
    'aeronaut tinkerer': 'Playable',
    'military intelligence': "Playable",
    'burning anger': 'Best',
    'plummet': "Playable",
    'frenzied goblin': 'Playable',
    'siege wurm': 'Playable',
    'overwhelm': "Playable",
    'wall of mulch': "Playable",
    'staff of the death magus': 'Bad',
    "crowd's favor": 'Playable',
    'mercurial pretender': "Playable",
    'diffusion sliver': "Filler",
    'phyrexian revoker': "Playable",
    'paragon of eternal wilds': "Playable",
    'devouring light': 'Great',
    'void snare': "Playable",
    'scrapyard mongrel': 'Playable',
    'generator servant': 'Playable',
    'staff of the wild magus': 'Bad',
    'aetherspouts': 'Playable',
    'child of night': 'Playable',
    'hammerhand': "Filler",
    'blood host': "Playable",
    'gravedigger': 'Playable',
    'divination': "Playable",
    'chandra, pyromaster': 'Good',
    'warden of the beyond': "Playable",
    'ob nixilis, unshackled': "Good",
    'juggernaut': 'Good',
    'bronze sable': "Playable",
    'jace, the living guildpact': 'Playable',
    'quickling': 'Playable',
    'caustic tar': "Playable",
    "jace's ingenuity": 'Playable',
    "rogue's gloves": "Playable",
    'phytotitan': 'Playable',
    'amphin pathmage': "Playable",
    'kurkesh, onakke ancient': 'Playable',
    'constricting sliver': "Playable",
    'paragon of fierce defiance': 'Playable',
    'eternal thirst': "Filler",
    'shadowcloak vampire': 'Playable',
    'ornithopter': "Filler",
    'soulmender': "Playable",
    'boonweaver giant': "Filler",
    'statute of denial': "Filler",
    'dauntless river marshal': 'Playable',
    'crucible of fire': 'Bad',
    'evolving wilds': 'Playable',
    'thundering giant': "Playable",
    'nissa, worldwaker': 'Best',
    'festergloom': "Playable",
    'clear a path': 'Bad',
    'darksteel citadel': "Filler",
    'soul of theros': 'Best',
    'oppressive rays': "Playable",
    'radiant fountain': "Filler",
    'indulgent tormentor': 'Best',
    'staff of the sun magus': 'Bad',
    'chronostutter': "Filler",
    "hunter's ambush": "Playable",
    'lava axe': "Filler",
    'kird chieftain': 'Great',
    'gargoyle sentinel': 'Good',
    'hornet queen': 'Best',
    'stoke the flames': 'Great',
    'mind sculpt': "Filler",
    'garruk, apex predator': 'Good',
    'geist of the moors': 'Playable',
    "krenko's enforcer": 'Playable',
    'llanowar wastes': 'Playable',
    'wall of frost': "Playable",
    'sliver hivelord': "Filler",
    'sliver hive': "Filler",
    'waste not': 'Bad',
    "witch's familiar": "Playable",
    'liliana vess': "Good",
    'urborg, tomb of yawgmoth': "Playable",
    'negate': "Playable",
    'coral barrier': "Playable",
    'runeclaw bear': "Playable",
    'tireless missionaries': "Filler",
    'rotfeaster maggot': 'Playable',
    'circle of flame': "Filler",
    'satyr wayfinder': 'Playable',
    "tormod's crypt": 'Bad',
    'xathrid slyblade': 'Playable',
    'meteorite': "Playable",
    'cruel sadist': 'Playable',
    'shaman of spring': "Playable",
    'hunt the weak': 'Playable',
    'ajani steadfast': 'Best',
    'jorubai murk lurker': 'Playable',
    'cone of flame': 'Best',
    'caves of koilos': 'Playable',
    'endless obedience': "Playable",
    'battlefield forge': 'Playable',
    'dissipate': "Playable",
    "necromancer's assistant": "Playable",
    'chief engineer': "Playable",
    'sacred armory': "Filler",
    'necrogen scudder': 'Playable',
    'paragon of gathering mists': "Playable",
    'fugitive wizard': "Filler",
    'spectra ward': 'Best',
    'leeching sliver': "Filler",
    'stain the mind': 'Bad',
    'rummaging goblin': 'Playable',
    'pillar of light': "Playable",
    'battle mastery': "Filler",
    'sunblade elf': 'Playable',
    'living totem': 'Playable',
    'shivan reef': 'Playable',
    'soul of ravnica': 'Best',
    'kalonian twingrove': 'Playable',
    'obelisk of urd': "Filler",
    "tyrant's machine": "Filler",
    'wall of essence': "Filler",
    "ranger's guile": "Playable",
    'restock': "Playable",
    'mass calcify': "Playable",
    'shield of the avatar': "Filler",
    'soul of new phyrexia': 'Good',
    'zof shade': 'Playable',
    'divine favor': "Filler",
    "nissa's expedition": "Filler",
    'hydrosurge': "Filler",
    'avacyn, guardian angel': 'Best',
    'spirit bonds': 'Best',
    'turn to frog': 'Playable',
    'will-forged golem': 'Playable',
    'selfless cathar': 'Playable',
    'nimbus of the isles': 'Playable',
    'avarice amulet': "Filler",
    'black cat': "Playable",
    'illusory angel': "Good",
    'stab wound': 'Great',
    'goblin kaboomist': 'Playable',
    'borderland marauder': "Good",
    'elvish mystic': "Good",
    'sign in blood': "Playable",
    'frost lynx': 'Playable',
    'necrobite': 'Playable',
    'mind rot': "Playable",
    'naturalize': "Filler",
    'inferno fist': 'Playable',
    'foundry street denizen': "Playable",
    'act on impulse': "Filler",
    'staff of the mind magus': 'Bad',
    'covenant of blood': 'Playable',
    'hot soup': "Filler",
    'reclamation sage': 'Playable',
    'paragon of new dawns': 'Playable',
    "ajani's pridemate": 'Playable',
    'soul of innistrad': 'Good',
    'altac bloodseeker': 'Playable',
    "in garruk's wake": "Filler",
    'goblin roughrider': 'Playable',
    'unmake the graves': "Filler",
    'ephemeral shields': "Playable",
    "polymorphist's jest": 'Good',
    'staff of the flame magus': 'Bad',
    'undergrowth scavenger': 'Playable',
    'typhoid rats': 'Playable',
    'the chain veil': 'Bad',
    'accursed spirit': 'Playable',
    'genesis hydra': 'Playable',
    'nightfire giant': "Good",
    'hornet nest': "Good",
    'carnivorous moss-beast': "Filler",
    'goblin rabblemaster': "Good",
    "heliod's pilgrim": 'Playable',
    'carrion crow': 'Playable',
    "necromancer's stockpile": "Filler",
    'hoarding dragon': 'Best',
    'back to nature': "Filler",
    'glacial crasher': "Playable",
    'marked by honor': "Playable",
    'brood keeper': 'Playable',
    'jalira, master polymorphist': "Playable",
    'feral incarnation': "Playable",
    'oreskos swiftclaw': "Playable",
    'gather courage': 'Playable',
    "life's legacy": "Filler",
    'venom sliver': "Playable",
    'blastfire bolt': "Playable",
    'kapsho kitefins': "Playable",
    'raise the alarm': 'Playable',
    'yisan, the wanderer bard': 'Good',
    'razorfoot griffin': "Playable",
    'soul of zendikar': 'Best',
    'return to the ranks': "Filler",
    'meditation puzzle': 'Bad',
    // Khans of Tarkir
    'disdainful stroke': 'Filler',
    'tuskguard captain': 'Good',
    'dragon throne of tarkir': 'Filler',
    'jeskai ascendancy': 'Filler',
    'despise': 'Filler',
    'temur ascendancy': 'Filler',
    'trap essence': 'Filler',
    'jeering instigator': 'Best',
    'armament corps': 'Good',
    'gurmag swiftwing': 'Filler',
    'mardu blazebringer': 'Filler',
    'summit prowler': 'Good',
    'mer-ek nightblade': 'Playable',
    'pine walker': 'Great',
    'mantis rider': 'Good',
    'crackling doom': 'Good',
    'take up arms': 'Filler',
    'rush of battle': 'Filler',
    'blossoming sands': 'Playable',
    'sagu archer': 'Filler',
    'stubborn denial': 'Bad',
    'woolly loxodon': 'Playable',
    'thousand winds': 'Best',
    'sultai scavenger': 'Playable',
    'incremental growth': 'Playable',
    'end hostilities': 'Good',
    'dismal backwater': 'Playable',
    'mardu skullhunter': 'Playable',
    "crater's claws": 'Best',
    'grim haruspex': 'Best',
    'timely hordemate': 'Playable',
    'dead drop': 'Filler',
    'clever impersonator': 'Playable',
    'rite of the serpent': 'Filler',
    'shambling attendants': 'Filler',
    'bloodstained mire': 'Playable',
    'polluted delta': 'Playable',
    'witness of the ages': 'Playable',
    'blinding spray': 'Filler',
    'efreet weaponmaster': 'Filler',
    'shatter': 'Bad',
    'dig through time': 'Playable',
    'winterflame': 'Good',
    'heir of the wilds': 'Great',
    'hooting mandrills': 'Filler',
    'heart-piercer bow': 'Filler',
    'burn away': 'Good',
    'ponyback brigade': 'Filler',
    'debilitating injury': 'Good',
    'riverwheel aerialists': 'Playable',
    'bring low': 'Good',
    'firehoof cavalry': 'Filler',
    'ainok bond-kin': 'Good',
    'temur banner': 'Filler',
    'monastery flock': 'Filler',
    'opulent palace': 'Playable',
    'jeskai charm': 'Good',
    'canyon lurkers': 'Filler',
    'butcher of the horde': 'Good',
    'bitter revelation': 'Filler',
    'avalanche tusker': 'Good',
    "dragon's eye savants": 'Good',
    'kheru spellsnatcher': 'Best',
    'crippling chill': 'Great',
    'mardu ascendancy': 'Filler',
    'sagu mauler': 'Best',
    'embodiment of spring': 'Filler',
    'mystic of the hidden way': 'Great',
    'hooded hydra': 'Best',
    "bear's companion": 'Good',
    'pearl lake ancient': 'Filler',
    'act of treason': 'Filler',
    'erase': 'Bad',
    'unyielding krumar': 'Filler',
    'savage punch': 'Good',
    'windstorm': 'Bad',
    'scion of glaciers': 'Great',
    'siegecraft': 'Filler',
    "raiders' spoils": 'Playable',
    'ruthless ripper': 'Good',
    'mindswipe': 'Filler',
    'dragon grip': 'Filler',
    'tomb of the spirit dragon': 'Bad',
    'become immense': 'Filler',
    'abzan falconer': 'Great',
    'glacial stalker': 'Good',
    'alabaster kirin': 'Good',
    'whirlwind adept': 'Filler',
    'herald of anafenza': 'Good',
    'temur charger': 'Good',
    'set adrift': 'Filler',
    'disowned ancestor': 'Filler',
    'smite the monstrous': 'Filler',
    'brave the sands': 'Bad',
    'savage knuckleblade': 'Good',
    'jeskai banner': 'Filler',
    'wetland sambar': 'Filler',
    'mardu banner': 'Filler',
    'sultai banner': 'Filler',
    'dragon-style twins': 'Good',
    'sorin, solemn visitor': 'Good',
    'ankle shanker': 'Good',
    'howl of the horde': 'Bad',
    'snowhorn rider': 'Good',
    'retribution of the ancients': 'Filler',
    'singing bell strike': 'Playable',
    'tusked colossodon': 'Filler',
    'murderous cut': 'Great',
    'sage of the inward eye': 'Good',
    'rakshasa vizier': 'Good',
    'ivorytusk fortress': 'Good',
    'jungle hollow': 'Playable',
    'dragonscale boon': 'Playable',
    'alpine grizzly': 'Filler',
    'high sentinels of arashin': 'Best',
    'leaping master': 'Filler',
    'defiant strike': 'Filler',
    'krumar bond-kin': 'Playable',
    'scout the borders': 'Filler',
    'kheru dreadmaw': 'Filler',
    'smoke teller': 'Filler',
    'weave fate': 'Filler',
    'valley dasher': 'Filler',
    'kin-tree invocation': 'Good',
    'hordeling outburst': 'Filler',
    'lens of clarity': 'Bad',
    'longshot squad': 'Playable',
    'altar of the brood': 'Bad',
    'sultai soothsayer': 'Good',
    "archers' parapet": 'Filler',
    'highspire mantis': 'Good',
    'frontier bivouac': 'Playable',
    'bellowing saddlebrute': 'Great',
    'mardu hordechief': 'Playable',
    'swift kick': 'Filler',
    'war behemoth': 'Playable',
    'cancel': 'Filler',
    "sidisi's pet": 'Filler',
    'ainok tracker': 'Filler',
    'kheru lich lord': 'Filler',
    'zurgo helmsmasher': 'Good',
    'abzan battle priest': 'Filler',
    'empty the pits': 'Filler',
    'mistfire weaver': 'Great',
    'waterwhirl': 'Filler',
    'seeker of the way': 'Great',
    'jeskai elder': 'Filler',
    'monastery swiftspear': 'Filler',
    'bloodsoaked champion': 'Playable',
    'suspension field': 'Great',
    'windswept heath': 'Playable',
    'dazzling ramparts': 'Filler',
    'goblinslide': 'Bad',
    'war-name aspirant': 'Playable',
    'mardu hateblade': 'Filler',
    'flying crane technique': 'Good',
    'seek the horizon': 'Filler',
    'thornwood falls': 'Playable',
    'abzan charm': 'Good',
    'force away': 'Playable',
    'icy blast': 'Good',
    "briber's purse": 'Filler',
    'master the way': 'Good',
    'secret plans': 'Filler',
    'mardu heart-piercer': 'Great',
    'swiftwater cliffs': 'Playable',
    'watcher of the roost': 'Good',
    'surrak dragonclaw': 'Good',
    'treasure cruise': 'Filler',
    'bloodfire expert': 'Filler',
    'nomad outpost': 'Playable',
    'tranquil cove': 'Playable',
    'bloodfire mentor': 'Filler',
    'anafenza, the foremost': 'Good',
    'molting snakeskin': 'Bad',
    'venerable lammasu': 'Filler',
    'throttle': 'Playable',
    'duneblast': 'Best',
    'bloodfell caves': 'Playable',
    'jeskai windscout': 'Great',
    "ugin's nexus": 'Bad',
    'mystic monastery': 'Playable',
    'rugged highlands': 'Playable',
    'mardu roughrider': 'Good',
    'flooded strand': 'Playable',
    'wind-scarred crag': 'Playable',
    'abzan ascendancy': 'Good',
    'death frenzy': 'Filler',
    'sultai flayer': 'Good',
    'arc lightning': 'Great',
    'warden of the eye': 'Filler',
    'scaldkin': 'Filler',
    'naturalize': 'Bad',
    'wingmate roc': 'Best',
    'trail of mystery': 'Filler',
    'wooded foothills': 'Playable',
    'roar of challenge': 'Playable',
    'sidisi, brood tyrant': 'Good',
    "rakshasa's secret": 'Filler',
    'icefeather aven': 'Great',
    'siege rhino': 'Good',
    'rakshasa deathdealer': 'Good',
    'ashcloud phoenix': 'Best',
    'feat of resistance': 'Good',
    'meandering towershell': 'Filler',
    'temur charm': 'Good',
    'utter end': 'Good',
    'abzan guide': 'Good',
    'barrage of boulders': 'Filler',
    'necropolis fiend': 'Good',
    'cranial archive': 'Bad',
    'jeskai student': 'Filler',
    'mardu warshrieker': 'Good',
    'sage-eye harrier': 'Filler',
    'abomination of gudul': 'Good',
    'kin-tree warden': 'Filler',
    "taigam's scheming": 'Bad',
    'chief of the edge': 'Good',
    'sultai charm': 'Good',
    'abzan banner': 'Filler',
    'chief of the scale': 'Good',
    'awaken the bear': 'Filler',
    'rotting mastodon': 'Filler',
    'scoured barrens': 'Playable',
    'swarm of bloodflies': 'Filler',
    'trumpet blast': 'Filler',
    'deflecting palm': 'Filler',
    'highland game': 'Filler',
    'arrow storm': 'Good',
    'ghostfire blade': 'Best',
    'quiet contemplation': 'Filler',
    'sultai ascendancy': 'Filler',
    'kheru bloodsucker': 'Filler',
    'kill shot': 'Filler',
    'ride down': 'Good',
    'mardu charm': 'Good',
    'hardened scales': 'Filler',
    'feed the clan': 'Bad',
    'see the unwritten': 'Good',
    'villainous wealth': 'Filler',
    'rattleclaw mystic': 'Best',
    'sandsteppe citadel': 'Playable',
    'sarkhan, the dragonspeaker': 'Best',
    'dutiful return': 'Filler',
    'horde ambusher': 'Good',
    'tormenting voice': 'Filler',
    'salt road patrol': 'Filler',
    'master of pearls': 'Best',
    'narset, enlightened master': 'Filler',
    // Fate reforged
    'mindscour dragon': 'Playable',
    'outpost siege': 'Best',
    'frontier mastodon': 'Playable',
    'abzan advantage': 'Bad',
    'abzan skycaptain': 'Good',
    'gurmag angler': 'Playable',
    'hooded assassin': 'Playable',
    'ainok guide': 'Playable',
    'monastery siege': 'Playable',
    'blossoming sands': 'Good',
    'cached defenses': 'Filler',
    'mistfire adept': 'Great',
    'refocus': 'Filler',
    'merciless executioner': 'Good',
    'dismal backwater': 'Good',
    'channel harm': 'Playable',
    'vaultbreaker': 'Playable',
    'soulflayer': 'Good',
    'polluted delta': 'Good',
    'torrent elemental': 'Best',
    'fierce invocation': 'Filler',
    'collateral damage': 'Filler',
    "hero's blade": 'Filler',
    'alesha, who smiles at death': 'Great',
    'pressure point': 'Playable',
    "honor's reward": 'Good',
    'lotus path djinn': 'Good',
    'grave strength': 'Bad',
    'temporal trespass': 'Bad',
    'palace siege': 'Great',
    'jeskai sage': 'Playable',
    'sibsig muckdraggers': 'Playable',
    'rite of undoing': 'Playable',
    'lotus-eye mystics': 'Filler',
    'temur sabertooth': 'Great',
    'break through the line': 'Filler',
    'cunning strike': 'Good',
    'battle brawler': 'Good',
    'sandsteppe outcast': 'Good',
    'lightning shrieker': 'Bad',
    'dromoka, the eternal': 'Best',
    'great-horn krushok': 'Filler',
    'war flare': 'Good',
    'ruthless instincts': 'Filler',
    'citadel siege': 'Best',
    'mardu woe-reaper': 'Good',
    'feral krushok': 'Playable',
    'diplomacy of the wastes': 'Bad',
    'abzan runemark': 'Filler',
    'warden of the first tree': 'Great',
    'neutralizing blast': 'Bad',
    'douse in gloom': 'Good',
    'ugin, the spirit dragon': 'Good',
    'ghastly conscription': 'Playable',
    'atarka, world render': 'Good',
    'mardu shadowspear': 'Bad',
    'smoldering efreet': 'Filler',
    'temur battle rage': 'Filler',
    'grim contest': 'Good',
    'reach of shadows': 'Good',
    'sultai emissary': 'Playable',
    'ojutai, soul of winter': 'Good',
    'orc sureshot': 'Good',
    'rageform': 'Playable',
    'battlefront krushok': 'Filler',
    'mardu runemark': 'Filler',
    "rakshasa's disdain": 'Bad',
    'sibsig host': 'Filler',
    'supplant form': 'Great',
    'sultai runemark': 'Filler',
    "ugin's construct": 'Playable',
    'mardu scout': 'Playable',
    "alesha's vanguard": 'Filler',
    'fearsome awakening': 'Filler',
    'jungle hollow': 'Good',
    'lightform': 'Great',
    'friendly fire': 'Filler',
    'brutal hordechief': 'Best',
    'dragon bell monk': 'Playable',
    'frontier siege': 'Bad',
    'goblin boom keg': 'Bad',
    'dragonrage': 'Filler',
    'hewed stone retainers': 'Filler',
    'tasigur, the golden fang': 'Great',
    'shockmaw dragon': 'Playable',
    'flamerush rider': 'Great',
    'noxious dragon': 'Good',
    'mardu strike leader': 'Great',
    'defiant ogre': 'Filler',
    'arcbond': 'Playable',
    'jeskai barricade': 'Playable',
    'yasova dragonclaw': 'Best',
    'soul summons': 'Good',
    'sandsteppe mastodon': 'Good',
    'bloodfire enforcers': 'Filler',
    'soulfire grand master': 'Great',
    'pilgrim of the fires': 'Filler',
    'whisk away': 'Good',
    'abzan beastmaster': 'Good',
    'flamewake phoenix': 'Great',
    'elite scaleguard': 'Great',
    'marang river prowler': 'Good',
    'hunt the weak': 'Good',
    'temur runemark': 'Filler',
    'ancestral vengeance': 'Filler',
    "sage's reverie": 'Bad',
    'windswept heath': 'Good',
    'shifting loyalties': 'Filler',
    'shamanic revelation': 'Playable',
    'archers of qarsi': 'Filler',
    "tasigur's cruelty": 'Bad',
    'thornwood falls': 'Good',
    'fascination': 'Bad',
    'humble defector': 'Playable',
    'formless nurturing': 'Filler',
    'sultai skullkeeper': 'Playable',
    'whisperer of the wilds': 'Good',
    'goblin heelcutter': 'Good',
    'aven surveyor': 'Good',
    'swiftwater cliffs': 'Good',
    'daghatar the adamant': 'Best',
    'mob rule': 'Great',
    'tranquil cove': 'Good',
    'dark deal': 'Bad',
    'bloodstained mire': 'Good',
    'ambush krotiq': 'Bad',
    'bloodfell caves': 'Good',
    'rally the ancestors': 'Bad',
    'sandblast': 'Good',
    'gore swine': 'Playable',
    'rugged highlands': 'Good',
    'wardscale dragon': 'Playable',
    'flooded strand': 'Good',
    'wind-scarred crag': 'Good',
    'reality shift': 'Filler',
    'enhanced awareness': 'Filler',
    'sage-eye avengers': 'Best',
    'scroll of the masters': 'Bad',
    'wooded foothills': 'Good',
    'valorous stance': 'Great',
    'silumgar, the drifting death': 'Great',
    'fruit of the first tree': 'Bad',
    'destructor dragon': 'Good',
    'bathe in dragonfire': 'Good',
    'qarsi high priest': 'Filler',
    'wild slash': 'Great',
    'temur war shaman': 'Best',
    'wildcall': 'Great',
    'archfiend of depravity': 'Best',
    'wandering champion': 'Good',
    'crucible of the spirit dragon': 'Bad',
    'sudden reclamation': 'Filler',
    "kolaghan, the storm's fury": 'Best',
    'renowned weaponsmith': 'Filler',
    'winds of qal sisma': 'Filler',
    'frost walker': 'Good',
    'ethereal ambush': 'Good',
    'shaman of the great hunt': 'Best',
    'monastery mentor': 'Great',
    'scoured barrens': 'Good',
    'abzan kin-guard': 'Playable',
    'arashin cleric': 'Bad',
    'harsh sustenance': 'Good',
    'whisperwood elemental': 'Best',
    'map the wastes': 'Filler',
    'write into being': 'Good',
    'pyrotechnics': 'Great',
    'cloudform': 'Good',
    'aven skirmisher': 'Filler',
    'shu yun, the silent tempest': 'Great',
    'hungering yeti': 'Filler',
    'dragonscale general': 'Great',
    'crux of fate': 'Great',
    'mastery of the unseen': 'Great',
    'jeskai infiltrator': 'Best',
    'return to the earth': 'Filler',
    'typhoid rats': 'Good',
    'will of the naga': 'Playable',
    'arashin war beast': 'Filler',
    'jeskai runemark': 'Good',
    // Dragons of Tarkir
    'press the advantage': 'Good',
    'silumgar assassin': 'Great',
    'dragonlord atarka': 'Best',
    'lightwalker': 'Playable',
    'hand of silumgar': 'Playable',
    'glaring aegis': 'Filler',
    'updraft elemental': 'Filler',
    'deathmist raptor': 'Best',
    'summit prowler': 'Playable',
    "sarkhan's triumph": 'Bad',
    'kolaghan forerunners': 'Playable',
    'kolaghan stormsinger': 'Filler',
    'sibsig icebreakers': 'Filler',
    'sidisi, undead vizier': 'Best',
    'icefall regent': 'Best',
    'myth realized': 'Playable',
    'coat with venom': 'Playable',
    'enduring victory': 'Playable',
    'assault formation': 'Playable',
    "sunbringer's touch": 'Filler',
    "butcher's glee": 'Playable',
    'student of ojutai': 'Filler',
    'graceblade artisan': 'Filler',
    'magmatic chasm': 'Bad',
    "taigam's strike": 'Filler',
    'sprinting warbrute': 'Playable',
    'gravepurge': 'Bad',
    'hidden dragonslayer': 'Best',
    'skywise teachings': 'Bad',
    'deathbringer regent': 'Best',
    'strongarm monk': 'Playable',
    'kolaghan monument': 'Filler',
    'anafenza, kin-tree spirit': 'Great',
    "dragonlord's prerogative": 'Good',
    "great teacher's decree": 'Filler',
    'negate': 'Bad',
    'virulent plague': 'Bad',
    'aerie bowmasters': 'Good',
    'foul-tongue invocation': 'Filler',
    'risen executioner': 'Playable',
    'arashin foremost': 'Great',
    'reckless imp': 'Playable',
    'ojutai exemplars': 'Best',
    'death wind': 'Great',
    'sheltered aerie': 'Bad',
    'thunderbreak regent': 'Best',
    'contradict': 'Bad',
    'swift warkite': 'Good',
    'artful maneuver': 'Playable',
    'savage ventmaw': 'Playable',
    'tail slash': 'Good',
    'lurking arynx': 'Playable',
    'roast': 'Great',
    'center soul': 'Filler',
    'marsh hulk': 'Playable',
    'echoes of the kin tree': 'Bad',
    'living lore': 'Bad',
    'tapestry of the ages': 'Bad',
    'tread upon': 'Filler',
    "dragonlord's servant": 'Filler',
    "berserkers' onslaught": 'Great',
    'conifer strider': 'Filler',
    'display of dominance': 'Bad',
    'void squall': 'Filler',
    'ainok artillerist': 'Filler',
    'misthoof kirin': 'Good',
    "ojutai's command": 'Playable',
    'segmented krotiq': 'Playable',
    'dragonlord dromoka': 'Best',
    'flatten': 'Good',
    "dromoka's command": 'Good',
    'damnable pact': 'Playable',
    'boltwing marauder': 'Best',
    'kolaghan skirmisher': 'Filler',
    'gudul lurker': 'Playable',
    'profound journey': 'Bad',
    'shape the sands': 'Bad',
    'dragonlord ojutai': 'Best',
    "hedonist's trove": 'Bad',
    'salt road ambushers': 'Playable',
    'dance of the skywise': 'Bad',
    'dragonlord silumgar': 'Best',
    'stormwing dragon': 'Good',
    "sidisi's faithful": 'Filler',
    'minister of pain': 'Playable',
    'sandcrafter mage': 'Playable',
    'sandstorm charger': 'Filler',
    'volcanic vision': 'Good',
    'learn from the past': 'Bad',
    'aven sunstriker': 'Good',
    'avatar of the resolute': 'Good',
    'dragon fodder': 'Filler',
    'warbringer': 'Playable',
    'shorecrasher elemental': 'Great',
    'sight beyond sight': 'Playable',
    'encase in ice': 'Playable',
    'dutiful attendant': 'Filler',
    'kolaghan aspirant': 'Playable',
    'resupply': 'Bad',
    'evolving wilds': 'Playable',
    'mystic meditation': 'Filler',
    'dromoka captain': 'Good',
    "atarka's command": 'Playable',
    'hardened berserker': 'Playable',
    'herald of dromoka': 'Filler',
    'rakshasa gravecaller': 'Great',
    'seismic rupture': 'Filler',
    'deadly wanderings': 'Filler',
    'dromoka dunecaster': 'Filler',
    'palace familiar': 'Good',
    'arashin sovereign': 'Playable',
    'foe-razer regent': 'Best',
    'dromoka warrior': 'Playable',
    'mirror mockery': 'Playable',
    'territorial roc': 'Filler',
    'draconic roar': 'Great',
    'defeat': 'Playable',
    'dragonlord kolaghan': 'Best',
    'colossodon yearling': 'Playable',
    'sabertooth outrider': 'Playable',
    'ukud cobra': 'Great',
    'necromaster dragon': 'Best',
    'herdchaser dragon': 'Playable',
    'belltoll dragon': 'Good',
    "silumgar's scorn": 'Bad',
    'lightning berserker': 'Filler',
    'sunscorch regent': 'Best',
    'stratus dancer': 'Great',
    'vial of dragonfire': 'Filler',
    "kolaghan's command": 'Great',
    'gate smasher': 'Bad',
    'monastery loremaster': 'Playable',
    'rending volley': 'Filler',
    'fate forgotten': 'Bad',
    'ojutai interceptor': 'Good',
    'guardian shield-bearer': 'Playable',
    'dragonloft idol': 'Playable',
    'dirgur nemesis': 'Bad',
    'atarka efreet': 'Good',
    'kindled fury': 'Filler',
    'clone legion': 'Bad',
    'foul-tongue shriek': 'Bad',
    'glade watcher': 'Good',
    "sarkhan's rage": 'Good',
    'atarka beastbreaker': 'Good',
    'spidersilk net': 'Bad',
    'radiant purge': 'Bad',
    'blood-chin rager': 'Good',
    'cunning breezedancer': 'Playable',
    'gurmag drowner': 'Good',
    'silumgar spell-eater': 'Playable',
    'pristine skywise': 'Good',
    'salt road quartermasters': 'Good',
    'dromoka monument': 'Filler',
    'shaman of forgotten ways': 'Great',
    'blessed reincarnation': 'Bad',
    'youthful scholar': 'Good',
    'keeper of the lens': 'Bad',
    'ancestral statue': 'Bad',
    'ancient carp': 'Filler',
    'pacifism': 'Good',
    'marang river skeleton': 'Playable',
    'explosive vegetation': 'Filler',
    'inspiring call': 'Bad',
    'ultimate price': 'Great',
    'silumgar monument': 'Filler',
    'scale blessing': 'Filler',
    'pinion feast': 'Filler',
    'profaner of the dead': 'Good',
    'battle mastery': 'Bad',
    'lose calm': 'Bad',
    'stampeding elk herd': 'Good',
    'dragon whisperer': 'Great',
    'qarsi deceiver': 'Bad',
    'atarka monument': 'Filler',
    'commune with lava': 'Filler',
    'qarsi sadist': 'Bad',
    'surge of righteousness': 'Filler',
    'anticipate': 'Filler',
    'narset transcendent': 'Playable',
    'haven of the spirit dragon': 'Bad',
    'zephyr scribe': 'Good',
    'wandering tombshell': 'Filler',
    'duress': 'Bad',
    'silkwrap': 'Good',
    'sight of the scalelords': 'Bad',
    'scaleguard sentinels': 'Good',
    'sandsteppe scavenger': 'Filler',
    'dragon tempest': 'Bad',
    'epic confrontation': 'Good',
    'descent of the dragons': 'Good',
    'vandalize': 'Bad',
    'circle of elders': 'Playable',
    'self-inflicted wound': 'Playable',
    'servant of the scale': 'Bad',
    'obscuring aether': 'Filler',
    'gleam of authority': 'Playable',
    'orator of ojutai': 'Bad',
    'pitiless horde': 'Good',
    'shambling goblin': 'Playable',
    "silumgar's command": 'Great',
    'dragon-scarred bear': 'Playable',
    'collected company': 'Bad',
    'secure the wastes': 'Great',
    'enduring scalelord': 'Playable',
    'shieldhide dragon': 'Good',
    'acid-spewer dragon': 'Good',
    'dragon hunter': 'Playable',
    'zurgo bellstriker': 'Good',
    'volcanic rush': 'Bad',
    'impact tremors': 'Bad',
    'reduce in stature': 'Filler',
    'revealing wind': 'Bad',
    'illusory gains': 'Playable',
    'harbinger of the hunt': 'Best',
    'mind rot': 'Bad',
    'atarka pummeler': 'Good',
    'ambuscade shaman': 'Playable',
    'silumgar sorcerer': 'Good',
    'stormrider rig': 'Bad',
    'corpseweft': 'Playable',
    'crater elemental': 'Great',
    'stormcrag elemental': 'Good',
    'foul renewal': 'Best',
    'surrak, the hunt caller': 'Best',
    'scion of ugin': 'Playable',
    'elusive spellfist': 'Filler',
    'blood-chin fanatic': 'Great',
    'silumgar butcher': 'Good',
    'ire shaman': 'Great',
    'custodian of the trove': 'Bad',
    "dromoka's gift": 'Playable',
    'ruthless deathfang': 'Good',
    'champion of arashin': 'Filler',
    "ojutai's summons": 'Good',
    'naturalize': 'Bad',
    "dragon's eye sentry": 'Bad',
    'den protector': 'Great',
    "ojutai's breath": 'Filler',
    'qal sisma behemoth': 'Playable',
    'twin bolt': 'Good',
    'tormenting voice': 'Playable',
    'ojutai monument': 'Filler',
    'aven tactician': 'Playable',
    'screamreach brawler': 'Filler',
    'glint': 'Bad',
    'ainok survivalist': 'Playable',
    'sarkhan unbroken': 'Great',
    'vulturous aven': 'Good',
    // Modern Masters 2015
    'thunderblust': 'Good',
    'kor duelist': 'Filler',
    'stoic rebuttal': 'Filler',
    'lightning bolt': 'Great',
    'thoughtcast': 'Filler',
    'copper carapace': 'Filler',
    'nest invader': 'Good',
    'waxmane baku': 'Good',
    'vines of vastwood': 'Filler',
    'sundering vitae': 'Filler',
    'flashfreeze': 'Bad',
    'endrek sahr, master breeder': 'Best',
    'fortify': 'Filler',
    'splinter twin': 'Filler',
    'kavu primarch': 'Filler',
    'somber hoverguard': 'Playable',
    'hellkite charger': 'Best',
    'vengeful rebirth': 'Good',
    'air servant': 'Great',
    'sunforger': 'Playable',
    "all suns' dawn": 'Playable',
    'expedition map': 'Filler',
    'cranial plating': 'Playable',
    'daggerclaw imp': 'Filler',
    'scion of the wild': 'Good',
    'cryptic command': 'Great',
    'arrest': 'Good',
    'narcolepsy': 'Good',
    'gut shot': 'Bad',
    'pillory of the sleepless': 'Great',
    'creakwood liege': 'Great',
    'myrsmith': 'Playable',
    'blood ogre': 'Good',
    'plaxcaster frogling': 'Playable',
    'nobilis of war': 'Good',
    'combust': 'Bad',
    'elesh norn, grand cenobite': 'Best',
    'mox opal': 'Filler',
    'steady progress': 'Filler',
    'boros swiftblade': 'Playable',
    'horde of notions': 'Bad',
    'shrewd hatchling': 'Good',
    'celestial purge': 'Bad',
    'leyline of sanctity': 'Bad',
    'dispatch': 'Playable',
    'scatter the seeds': 'Good',
    'wings of velis vel': 'Bad',
    'sphere of the suns': 'Filler',
    'guile': 'Good',
    'rusted relic': 'Playable',
    'matca rioters': 'Playable',
    'ghost council of orzhova': 'Great',
    'ghostly changeling': 'Filler',
    'bloodshot trainee': 'Playable',
    'darksteel axe': 'Good',
    'aquastrand spider': 'Filler',
    'faerie mechanist': 'Playable',
    'dread drone': 'Playable',
    'ulamog, the infinite gyre': 'Bad',
    'necrogenesis': 'Playable',
    'battlegrace angel': 'Best',
    'bone splinters': 'Playable',
    'dimir aqueduct': 'Good',
    'sunspear shikari': 'Playable',
    'hearthfire hobgoblin': 'Playable',
    'mirror entity': 'Best',
    'tumble magnet': 'Good',
    'blades of velis vel': 'Bad',
    'simic initiate': 'Bad',
    'noble hierarch': 'Great',
    'plummet': 'Bad',
    'kozilek, butcher of truth': 'Bad',
    'overwhelm': 'Filler',
    'swans of bryn argoll': 'Great',
    'kitesail': 'Filler',
    'flayer husk': 'Filler',
    'wolfbriar elemental': 'Best',
    'profane command': 'Best',
    'drooling groodion': 'Playable',
    'bitterblossom': 'Best',
    'electrolyze': 'Playable',
    'cloud elemental': 'Filler',
    'smokebraider': 'Playable',
    'deathmark': 'Filler',
    'vampire lacerator': 'Playable',
    'novijen sages': 'Filler',
    'precursor golem': 'Best',
    "wayfarer's bauble": 'Good',
    'shadowmage infiltrator': 'Playable',
    'kami of ancient law': 'Playable',
    'glassdust hulk': 'Playable',
    'skarrgan firebird': 'Good',
    'etched champion': 'Playable',
    'bloodthrone vampire': 'Playable',
    "ulamog's crusher": 'Filler',
    'chimeric mass': 'Good',
    'shrivel': 'Bad',
    'karn liberated': 'Best',
    'overwhelming stampede': 'Best',
    'spread the sickness': 'Good',
    'sickleslicer': 'Filler',
    'qumulox': 'Playable',
    'nameless inversion': 'Good',
    'runed servitor': 'Filler',
    'instill infection': 'Filler',
    'ant queen': 'Best',
    'telling time': 'Filler',
    'skyreach manta': 'Playable',
    'glint hawk idol': 'Playable',
    'alloy myr': 'Good',
    'gruul turf': 'Good',
    'duskhunter bat': 'Playable',
    'blinkmoth nexus': 'Playable',
    'fiery fall': 'Good',
    'moonlit strider': 'Playable',
    'evolving wilds': 'Good',
    'lodestone myr': 'Good',
    'spellskite': 'Good',
    'mystic snake': 'Playable',
    'rampant growth ': 'Playable',
    'restless apparition': 'Playable',
    'devouring greed': 'Playable',
    'death denied': 'Filler',
    'soulbright flamekin': 'Filler',
    'ashenmoor gouger': 'Playable',
    'surrakar spellblade': 'Filler',
    'brute force': 'Filler',
    'savage twister': 'Great',
    'waking nightmare': 'Bad',
    'tezzeret the seeker': 'Playable',
    'selesnya sanctuary': 'Good',
    "kozilek's predator": 'Good',
    'artisan of kozilek': 'Filler',
    'midnight banshee': 'Good',
    'indomitable archangel': 'Best',
    'sylvan bounty': 'Filler',
    'tribal flames': 'Good',
    'mighty leap ': 'Filler',
    'spectral procession': 'Great',
    'gorehorn minotaurs': 'Good',
    'thrummingbird': 'Good',
    'simic growth chamber': 'Good',
    'taj-nar swordsmith': 'Playable',
    'tarmogoyf': 'Filler',
    "tezzeret's gambit": 'Good',
    'goblin fireslinger': 'Playable',
    'pelakka wurm': 'Good',
    'wildfire': 'Good',
    'wrap in flames': 'Filler',
    'vigean graftmage': 'Bad',
    'worldheart phoenix': 'Playable',
    'mulldrifter': 'Great',
    'court homunculus': 'Playable',
    'selesnya guildmage': 'Great',
    "terashi's grasp": 'Filler',
    'tukatongue thallid': 'Filler',
    'emrakul, the aeons torn': 'Bad',
    'water servant': 'Good',
    'scavenger drake': 'Playable',
    'niv-mizzet, the firemind': 'Great',
    'wrecking ball': 'Playable',
    'primeval titan': 'Good',
    'conclave phalanx': 'Filler',
    'mirran crusader': 'Best',
    'ethercaste knight': 'Playable',
    'sunlance': 'Good',
    'root-kin ally': 'Playable',
    'apocalypse hydra': 'Good',
    'lodestone golem': 'Good',
    'inner-flame igniter': 'Filler',
    'oblivion ring': 'Great',
    'orzhov basilica': 'Good',
    'eldrazi temple': 'Bad',
    'argent sphinx': 'Best',
    'vampire outcasts': 'Good',
    'puppeteer clique': 'Best',
    'darksteel citadel': 'Filler',
    'lorescale coatl': 'Good',
    'rakdos carnarium': 'Good',
    'karplusan strider': 'Filler',
    'izzet boilerworks': 'Good',
    'mortarpod': 'Good',
    'reassembling skeleton': 'Filler',
    'eye of ugin': 'Bad',
    'spikeshot elder': 'Good',
    'commune with nature': 'Bad',
    'gnarlid pack': 'Filler',
    'vapor snag': 'Filler',
    'plagued rusalka': 'Good',
    'blinding souleater': 'Good',
    'helium squirter': 'Filler',
    'spitebellows': 'Good',
    'scute mob': 'Filler',
    'everflowing chalice': 'Filler',
    'scuttling death': 'Playable',
    'daybreak coronet': 'Bad',
    'etched monstrosity': 'Good',
    'otherworldly journey': 'Filler',
    'dimir guildmage': 'Great',
    'all is dust': 'Good',
    'bestial menace': 'Great',
    'sickle ripper': 'Filler',
    'necroskitter': 'Great',
    'etched oracle': 'Playable',
    'grim affliction': 'Good',
    'dismember': 'Great',
    'agony warp': 'Playable',
    'azorius chancery': 'Good',
    'culling dais': 'Filler',
    'sigil blessing': 'Playable',
    'remand': 'Good',
    'long-forgotten gohei': 'Filler',
    'thrive': 'Filler',
    'goblin war paint': 'Bad',
    'inexorable tide': 'Filler',
    'kiki-jiki, mirror breaker': 'Great',
    'algae gharial': 'Playable',
    'viashino slaughtermaster': 'Playable',
    'iona, shield of emeria': 'Filler',
    'burst lightning': 'Good',
    'golgari rot farm': 'Good',
    'banefire': 'Best',
    'frogmite': 'Bad',
    'wilt-leaf liege': 'Best',
    'gust-skimmer': 'Filler',
    'mana leak': 'Good',
    'sign in blood': 'Filler',
    'vendilion clique': 'Great',
    'cathodion': 'Good',
    'cytoplast root-kin': 'Great',
    "hurkyl's recall": 'Filler',
    'dark confidant': 'Good',
    'myr enforcer': 'Playable',
    'hikari, twilight guardian': 'Great',
    'repeal': 'Good',
    "apostle's blessing": 'Filler',
    'aethersnipe': 'Good',
    'mutagenic growth': 'Filler',
    'smash to smithereens': 'Filler',
    'stormblood berserker': 'Playable',
    'incandescent soulstoke': 'Playable',
    'thief of hope': 'Good',
    'dragonsoul knight': 'Filler',
    'fulminator mage': 'Good',
    'raise the alarm': 'Filler',
    'boros garrison': 'Good',
    'surgical extraction': 'Bad',
    'skyhunter skirmisher': 'Playable',
    'comet storm': 'Best',
    // Magic Origins
    'bonded construct': 'Filler',
    'orchard spirit': 'Playable',
    'touch of moonglove': 'Bad',
    'undead servant': 'Filler',
    'cobblebrute': 'Filler',
    'tragic arrogance': 'Best',
    'volcanic rambler': 'Filler',
    'tainted remedy': 'Bad',
    'talent of the telepath': 'Bad',
    'yavimaya coast': 'Playable',
    "nissa's revelation": 'Playable',
    'enshrouding mist': 'Good',
    'disperse': 'Playable',
    'stalwart aven': 'Good',
    'enlightened ascetic': 'Filler',
    "alhammarret's archive": 'Bad',
    'dark dabbling': 'Filler',
    'vine snare': 'Bad',
    'ghirapur gearcrafter': 'Good',
    'guardian automaton': 'Playable',
    "kytheon's irregulars": 'Best',
    "brawler's plate": 'Filler',
    'fleshbag marauder': 'Playable',
    'read the bones': 'Playable',
    'goblin piledriver': 'Bad',
    'mage-ring responder': 'Good',
    'sigil of valor': 'Playable',
    'bone to ash': 'Filler',
    'totem-guide hartebeest': 'Good',
    'anchor to the aether': 'Good',
    'consecrated by blood': 'Playable',
    'weight of the underworld': 'Filler',
    'shivan reef': 'Playable',
    "pharika's disciple": 'Good',
    "iroas's champion": 'Good',
    'orbs of warding': 'Bad',
    'ghirapur aether grid': 'Bad',
    'harbinger of the tides': 'Good',
    'auramancer': 'Filler',
    'herald of the pantheon': 'Playable',
    'tower geist': 'Good',
    'unholy hunger': 'Good',
    'meteorite': 'Filler',
    'elvish visionary': 'Good',
    'wild instincts': 'Good',
    'foundry of the consuls': 'Playable',
    'throwing knife': 'Good',
    'whirler rogue': 'Great',
    'ramroller': 'Playable',
    'rhox maulers': 'Good',
    'scrapskin drake': 'Playable',
    'joraga invocation': 'Good',
    'infectious bloodlust': 'Bad',
    'subterranean scout': 'Good',
    'skysnare spider': 'Good',
    'priest of the blood rite': 'Best',
    'eyeblight massacre': 'Playable',
    'managorger hydra': 'Best',
    'smash to smithereens': 'Bad',
    'displacement wave': 'Bad',
    'magmatic insight': 'Filler',
    'leaf gilder': 'Good',
    "veteran's sidearm": 'Filler',
    'citadel castellan': 'Good',
    'undercity troll': 'Great',
    'bellows lizard': 'Bad',
    'war horn': 'Bad',
    'shadows of the past': 'Filler',
    'maritime guard': 'Playable',
    "dwynen's elite": 'Good',
    'shaman of the pack': 'Good',
    'aerial volley': 'Filler',
    'act of treason': 'Playable',
    'tormented thoughts': 'Bad',
    'sentinel of the eternal watch': 'Great',
    'war oracle': 'Good',
    'skyraker giant': 'Good',
    'swift reckoning': 'Good',
    'deep-sea terror': 'Filler',
    "gaea's revenge": 'Playable',
    'jhessian thief': 'Good',
    'rabid bloodsucker': 'Filler',
    'mizzium meddler': 'Playable',
    'thunderclap wyvern': 'Good',
    'jace, telepath unbound': 'Best',
    'helm of the gods': 'Bad',
    'dark petition': 'Filler',
    "chandra's ignition": 'Best',
    'prism ring': 'Bad',
    'hixus, prison warden': 'Great',
    'claustrophobia': 'Good',
    'thopter spy network': 'Good',
    'chandra, roaring flame': 'Best',
    'nantuko husk': 'Good',
    'avaricious dragon': 'Good',
    'bounding krasis': 'Good',
    'exquisite firecraft': 'Great',
    'hitchclaw recluse': 'Playable',
    'runed servitor': 'Playable',
    'faerie miscreant': 'Filler',
    'dragon fodder': 'Playable',
    'nightsnare': 'Filler',
    'celestial flare': 'Good',
    'gideon, battle-forged': 'Best',
    'gold-forged sentinel': 'Playable',
    'mantle of webs': 'Bad',
    'deadbridge shaman': 'Good',
    'lightning javelin': 'Good',
    'embermaw hellion': 'Great',
    'nivix barrier': 'Filler',
    'ringwarden owl': 'Playable',
    'firefiend elemental': 'Playable',
    'guardians of meletis': 'Filler',
    "day's undoing": 'Bad',
    'akroan jailer': 'Filler',
    'revenant': 'Filler',
    'shambling ghoul': 'Good',
    'infinite obliteration': 'Bad',
    'dwynen, gilt-leaf daen': 'Good',
    'dreadwaters': 'Bad',
    "angel's tomb": 'Playable',
    'despoiler of souls': 'Filler',
    'kothophed, soul hoarder': 'Good',
    'reclaim': 'Bad',
    'nissa, vastwood seer': 'Best',
    'yoked ox': 'Bad',
    'vastwood gorger': 'Filler',
    'valeron wardens': 'Good',
    'llanowar wastes': 'Playable',
    'zendikar incarnate': 'Good',
    "kytheon's tactics": 'Filler',
    'kytheon, hero of akros': 'Best',
    'chief of the foundry': 'Good',
    'thopter engineer': 'Good',
    'archangel of tithes': 'Great',
    'graveblade marauder': 'Good',
    'cleric of the forward order': 'Good',
    'clash of wills': 'Filler',
    'llanowar empath': 'Good',
    'sword of the animist': 'Good',
    'screeching skaab': 'Playable',
    'negate': 'Filler',
    'disciple of the ring': 'Good',
    'scab-clan berserker': 'Good',
    'somberwald alpha': 'Good',
    'languish': 'Best',
    'reclusive artificer': 'Good',
    "jace's sanctum": 'Bad',
    'evolutionary leap': 'Filler',
    'honored hierarch': 'Filler',
    'necromantic summons': 'Playable',
    'molten vortex': 'Playable',
    'relic seeker': 'Good',
    "animist's awakening": 'Bad',
    'sigil of the empty throne': 'Bad',
    "alchemist's vial": 'Playable',
    'cruel revival': 'Good',
    'boggart brute': 'Good',
    'gather the pack': 'Filler',
    "rogue's passage": 'Good',
    'goblin glory chaser': 'Filler',
    'battlefield forge': 'Playable',
    'gilt-leaf winnower': 'Best',
    'infernal scarring': 'Filler',
    'heavy infantry': 'Filler',
    'eyeblight assassin': 'Playable',
    'send to sleep': 'Filler',
    'hangarback walker': 'Best',
    'sylvan messenger': 'Filler',
    "knight of the pilgrim's road": 'Playable',
    'gnarlroot trapper': 'Filler',
    'caustic caterpillar': 'Filler',
    'murder investigation': 'Bad',
    'mage-ring network': 'Bad',
    'nissa, sage animist': 'Best',
    'demolish': 'Bad',
    'liliana, defiant necromancer': 'Best',
    'caves of koilos': 'Playable',
    'might of the masses': 'Good',
    'starfield of nyx': 'Bad',
    'call of the full moon': 'Filler',
    "titan's strength": 'Playable',
    'demonic pact': 'Filler',
    'reave soul': 'Good',
    'jayemdae tome': 'Bad',
    'calculated dismissal': 'Filler',
    'hallowed moonlight': 'Bad',
    "sphinx's tutelage": 'Filler',
    'aven battle priest': 'Filler',
    'topan freeblade': 'Good',
    'soulblade djinn': 'Good',
    'seismic elemental': 'Great',
    'turn to frog': 'Filler',
    'watercourser': 'Playable',
    'mage-ring bully': 'Playable',
    'liliana, heretical healer': 'Best',
    "erebos's titan": 'Playable',
    'healing hands': 'Bad',
    'macabre waltz': 'Filler',
    'patron of the valiant': 'Good',
    'blessed spirits': 'Good',
    "chandra's fury": 'Filler',
    'chandra, fire of kaladesh': 'Best',
    "zendikar's roil": 'Filler',
    'malakir cullblade': 'Filler',
    'possessed skaab': 'Good',
    'ampryn tactician': 'Playable',
    'vryn wingmare': 'Playable',
    'charging griffin': 'Playable',
    'pia and kiran nalaar': 'Best',
    'returned centaur': 'Playable',
    'stratus walk': 'Filler',
    'psychic rebuttal': 'Bad',
    'thornbow archer': 'Filler',
    'acolyte of the inferno': 'Good',
    'the great aurora': 'Bad',
    'blightcaster': 'Playable',
    'valor in akros': 'Bad',
    'enthralling victor': 'Playable',
    'timberpack wolf': 'Good',
    'alhammarret, high arbiter': 'Good',
    "consul's lieutenant": 'Good',
    'ravaging blaze': 'Good',
    'aspiring aeronaut': 'Playable',
    "pyromancer's goggles": 'Bad',
    'mighty leap': 'Playable',
    'anointer of champions': 'Good',
    "nissa's pilgrimage": 'Filler',
    'fetid imp': 'Good',
    'evolving wilds': 'Good',
    'blazing hellhound': 'Good',
    'abbot of keral keep': 'Good',
    'skaab goliath': 'Playable',
    "jace, vryn's prodigy": 'Best',
    'suppression bonds': 'Good',
    "artificer's epiphany": 'Filler',
    'elemental bond': 'Bad',
    'catacomb slug': 'Filler',
    'fiery impulse': 'Good',
    'akroan sergeant': 'Good',
    'knight of the white orchid': 'Good',
    'conclave naturalists': 'Good',
    'blood-cursed knight': 'Playable',
    'willbreaker': 'Good',
    'flameshadow conjuring': 'Bad',
    'hydrolash': 'Filler',
    'grasp of the hieromancer': 'Playable',
    'separatist voidmage': 'Good',
    'fiery conclusion': 'Good',
    "gideon's phalanx": 'Good',
    'titanic growth': 'Good',
    'outland colossus': 'Best',
    "yeva's forcemage": 'Playable',
    'woodland bellower': 'Good',
    'prickleboar': 'Playable',
    'knightly valor': 'Great',
    'sigiled starfish': 'Good'
};
